#!/bin/bash
path=`pwd`
notify-send "Lazarone S. Santana" "Servidor de Desenvolvimento está no ar." -i "$path/image/server.svg"

#url='192.168.0.17:8000'
url='localhost:8000'
echo "Abrindo o Firefox em: $url"
firefox $url &

php -S $url
